name: 💡 Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to suggest a feature! Please fill out the sections below to help us understand your request.

  - type: textarea
    id: problem
    attributes:
      label: Problem Description
      description: |
        Is your feature request related to a problem? Please describe it.
        A clear and concise description of what the problem is.
      placeholder: "I'm always frustrated when..."
    validations:
      required: false

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see implemented.
      placeholder: "I would like to be able to..."
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions or features you've considered.
      placeholder: "I've also thought about..."
    validations:
      required: false

  - type: dropdown
    id: category
    attributes:
      label: Feature Category
      description: What area of the project does this feature relate to?
      options:
        - API / New methods or properties
        - Cloud Save functionality
        - Authentication / Authorization
        - DLC / Ownership management
        - Event handling
        - TypeScript types
        - Platform support
        - Developer experience / Tooling
        - Documentation
        - Other
    validations:
      required: true

  - type: textarea
    id: use_case
    attributes:
      label: Use Case
      description: |
        Describe the use case(s) that would benefit from this feature.
        This helps us understand the real-world application.
      placeholder: "This would be useful for..."
    validations:
      required: true

  - type: textarea
    id: api_design
    attributes:
      label: API Design (Optional)
      description: If you have ideas about how the API should look, share them here.
      render: typescript
      placeholder: |
        // Example usage:
        const sdk = new TapSdk('...');
        sdk.newFeature();

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, mockups, or screenshots about the feature request here.
      placeholder: Any additional information...

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I have searched existing issues and feature requests to make sure this isn't a duplicate
          required: true
        - label: I have read the documentation to check if this feature already exists
          required: true

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Would you be willing to help implement this feature?
      options:
        - label: I would be willing to submit a PR to implement this feature
          required: false
